version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
